the groovy file should wait for simpleci.conf file to generate before…
devopsnext/simpleci pull request #2
Opened 2018-04-09 09:18 UTC by nbansal16

… execution. Logic is added for that.

2018-04-09 10:51 UTC, amit04pandey commented on init.groovy.d/bitbucket-config.groovy
> +			out.println ("I am a test info log")
out.println ("Waiting for SimpleCI.conf file : Iteration $i")

2018-04-09 10:53 UTC, amit04pandey commented on init.groovy.d/bitbucket-config.groovy
> +			out.println ("Config file not present at the location. Please generate the file and try again later")
out.println ("Config file not present at the location $home_dir/simpleci.conf. Please generate the file and try again later")

2018-04-09 10:53 UTC, amit04pandey commented on init.groovy.d/config-init.groovy
> +		out.println ("I am a test info log")
similar comment as bitbucket-init.groovy

2018-04-09 10:54 UTC, amit04pandey commented on init.groovy.d/config-init.groovy
> +		out.println ("Config file not present at the location. Please generate the file and try again later")
similar comment as bitbucket-init.groovy to specify the target location in error message

2018-04-09 10:56 UTC, amit04pandey requested changes
Please review the comments and make corresponding changes

2018-04-10 11:12 UTC, Goldgod approved these changes
only return statement having doubt, instead we could try with sys.exit. Let me merge and test it out once.

2018-04-10 11:12 UTC, merged